// <auto-generated />
namespace MvcWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InitialAccountDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialAccountDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201901050814359_InitialAccountDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
